name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend Lint & Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: continuity-frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: continuity-frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Build
      run: npm run build

  backend:
    name: Backend Lint & Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies with uv
      run: uv sync

    - name: Lint with ruff (uvx)
      run: |
        uvx --from ruff ruff check --output-format=github .
        uvx --from ruff ruff format --check .

    - name: Test with pytest (uvx)
      run: uvx --from pytest pytest -q
